# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4605eefdcefc0634ef8de0212e01e10161da10df18a485ae081f2ab66b82176d6cd14f4261bfd1b6aa5558cb7e8f91acdf0af299d8551c58fbb760146d18450f

test:
  secret_key_base: abfbfb05466466faafea2b63209b3e1d0b2f480b6e5ab9f64bde912e15be2c049566fb48053c4cea56e9bcd813951e7b5ff17473d6efeaf488a49c86a8667a9c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
